In [3]:
import numpy as np
print(np.__version__)

2.2.3


In [7]:
#Creating array
list=[10,20,30,40,50,]
arr=np.array(list)
print(arr)
print("Data Type: ",type(arr))
print("Shape: ",arr.shape)

[10 20 30 40 50]
Data Type:  <class 'numpy.ndarray'>
Shape:  (5,)


In [14]:
#creating 1D and 2d array
arr1=np.array([[1,2,3],[4,5,6]])
print("Array: ",arr1)
print(" ")
print("no. of rows and columns: ",arr1.shape) #rows and column
print("Array size: ",arr1.size) #length
print(arr1[0]) # Accessing First Row
print(arr1[0][2])  # Accessing first row third column


Array:  [[1 2 3]
 [4 5 6]]
 
no. of rows and columns:  (2, 3)
Array size:  6
[1 2 3]
3


In [20]:
## Generate Arrays

arr1=np.zeros([2,3])  # 2X3 matrix filled with zeros
print("array of zeros:")
print(arr1)

print("-------------- ")
arr2=np.ones((3,3))
print("array of 1s:")
print(arr2)

print("---------------")
arr3=np.arange(1,10,3)
print(arr3)


array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
-------------- 
array of 1s:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---------------
[1 4 7]


In [23]:
sample_arr=np.array([np.arange(1,10,3),np.arange(2,10,3)])
print("Sample unique array: ")
print(sample_arr)

Sample unique array: 
[[1 4 7]
 [2 5 8]]


In [31]:


arr3=np.arange(1,10,3)
print(arr3)
arr4=np.arange(2,10,3)
print(arr4)
print(" ")
print('-----Addition-------')
print(arr3+arr4)
print(' ')
print('-----Multiplication-------')
print(arr3*arr4) 
print(" ")
print('----square-------')
print(arr3**2)

[1 4 7]
[2 5 8]
 
-----Addition-------
[ 3  9 15]
 
-----Multiplication-------
[ 2 20 56]
 
----square-------
[ 1 16 49]


In [35]:
purchases=np.array([
    [200,150,100],
    [300,250,400],
    [100,200,150],
    [500,600,550],
    [50,80,100]
])

total_spend = purchases.sum(axis=1)


average_spend= purchases.mean(axis=1)
print("Total spend: ",total_spend)
print("average_spend: ",average_spend)
print("Average maximum spend: ",(max(average_spend)))

Total spend:  [ 450  950  450 1650  230]
average_spend:  [150.         316.66666667 150.         550.          76.66666667]
Average maximum spend:  550.0


In [37]:
# SOLVING QUADRATIC EQUATION
#2X+3Y=8
#4X+Y=10

#Coefficients of Variable 
A=np.array([[2,3],[4,1]])

#Constants
B=np.array([8,10])

#Solve 
solution=np.linalg.solve(A , B)
print("Solution for(X,Y): ",solution)


Solution for(X,Y):  [2.2 1.2]


In [51]:
#Assignment assuming 10 days sales data

sales=np.array([1500,2500,5000,3000,7000,8000,4000,1000,3500,2500])
Total_sales=sum(sales)
Average_sales=np.average(sales)
max_sales=np.max(sales)
min_sales=np.min(sales)
print("------BASIC ANALYSIS OF SALES DATA-----!!")
print("Total_Sales: ",Total_sales)
print("Average_Sales: ",Average_sales)
print("Maximum_Sales: ",max_sales)
print("Minimum_sales: ",min_sales)
print(" ")
print("Sales Higher than average:",sales[sales>Average_sales])
updated_sales=sales*1.1
print("Updated Sales: ",updated_sales)
print(" ")
print("Sales data after sorting:",np.sort(sales))
               

------BASIC ANALYSIS OF SALES DATA-----!!
Total_Sales:  38000
Average_Sales:  3800.0
Maximum_Sales:  8000
Minimum_sales:  1000
 
Sales Higher than average: [5000 7000 8000 4000]
Updated Sales:  [1650. 2750. 5500. 3300. 7700. 8800. 4400. 1100. 3850. 2750.]
 
Sales data after sorting: [1000 1500 2500 2500 3000 3500 4000 5000 7000 8000]


In [54]:
import pandas as pd
df=pd.read_csv('sales_data.csv')
df.head()

Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           NaN   
1      1002  Mobile Phone  Electronics         1    500           NaN   
2      1003    Headphones  Accessories         3     50           NaN   
3      1004         Mouse  Accessories         2     20           NaN   
4      1005      Keyboard  Accessories         1     30           NaN   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05

In [58]:
df.isnull() #checking null value

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [59]:
df.fillna(0)

Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           0.0   
1      1002  Mobile Phone  Electronics         1    500           0.0   
2      1003    Headphones  Accessories         3     50           0.0   
3      1004         Mouse  Accessories         2     20           0.0   
4      1005      Keyboard  Accessories         1     30           0.0   
5      1006       T-shirt     Clothing         4     15           0.0   
6      1007        Jacket     Clothing         1     60           0.0   
7      1008  Refrigerator  Electronics         1    900           0.0   
8      1009            TV  Electronics         2   1100           0.0   
9      1010         Shoes     Clothing         2     40           0.0   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10

In [57]:
df.duplicated()  #checkking duplicates

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [61]:
print("Data Types: ")
df.dtypes

Data Types: 


Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [63]:
#converting date into date time
df['date']=pd.to_datetime(df['Date'])

In [65]:
df.dtypes

Order_ID                 int64
Product                 object
Category                object
Quantity                 int64
Price                    int64
Total_Amount           float64
Date                    object
date            datetime64[ns]
dtype: object

In [69]:
df['Product']=df['Product'].astype(str)
df['Category']=df['Category'].astype(str)


In [73]:
df.dtypes

A    object
B    object
dtype: object

In [75]:
#finding outlier

data=np.array([10,12,14,15,18,21,25,100])

#Calculate Q1,Q3 and IQR
Q1= np.percentile(data,25)
Q3=np.percentile(data,75)

IQR= Q3-Q1

#Define the bounds for outliers
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR

#Identify outliers
outliers = data[(data<lower_bound) |(data>upper_bound)]
print("Outliers: ",outliers)

Outliers:  [100]
